export type PlaceEntry = {
  id: string;
  text: string;
  secondary: string;
  type: "city" | "station" | "airport" | "village" | "town" | "hamlet" | "locality" | "place";
  country?: string;
  currency?: string;
  currencySymbol?: string;
  keywords?: string[];
  lat: number;
  lng: number;
};

export const COMPREHENSIVE_PLACES: PlaceEntry[] = [
  // --- INDIA - ANDHRA PRADESH & TELANGANA ---
  {
    id: "in-vja",
    text: "Vijayawada",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bezawada", "vja", "bza"],
    lat: 16.5062,
    lng: 80.648,
  },
  {
    id: "in-vja-bza",
    text: "Vijayawada Junction Railway Station (BZA)",
    secondary: "Vijayawada, Andhra Pradesh, India",
    type: "station",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bza", "station"],
    lat: 16.518,
    lng: 80.619,
  },
  {
    id: "in-vja-vga",
    text: "Vijayawada International Airport (VGA)",
    secondary: "Gannavaram, Andhra Pradesh, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["gannavaram", "vga"],
    lat: 16.5304,
    lng: 80.7968,
  },
  {
    id: "in-hyd",
    text: "Hyderabad",
    secondary: "Telangana, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["hyd", "cyberabad", "secunderabad", "charminar", "hitec city"],
    lat: 17.385,
    lng: 78.4867,
  },
  {
    id: "in-hyd-sc",
    text: "Secunderabad Junction (SC)",
    secondary: "Hyderabad, Telangana, India",
    type: "station",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["secunderabad", "sc"],
    lat: 17.4339,
    lng: 78.5042,
  },
  {
    id: "in-hyd-rgia",
    text: "Rajiv Gandhi International Airport (HYD)",
    secondary: "Shamshabad, Hyderabad, Telangana, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["shamshabad", "rgia", "hyd"],
    lat: 17.2403,
    lng: 78.4294,
  },
  {
    id: "in-vskp",
    text: "Visakhapatnam",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["vizag", "vskp", "waltair"],
    lat: 17.6868,
    lng: 83.2185,
  },
  {
    id: "in-vskp-vtz",
    text: "Visakhapatnam Airport (VTZ)",
    secondary: "Visakhapatnam, Andhra Pradesh, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["vtz"],
    lat: 17.7215,
    lng: 83.2245,
  },
  {
    id: "in-tpty",
    text: "Tirupati",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["tpty", "tirumala", "balaji"],
    lat: 13.6288,
    lng: 79.4192,
  },
  {
    id: "in-bvr",
    text: "Bhimavaram",
    secondary: "West Godavari, Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bvr", "bvrm", "godavari"],
    lat: 16.5449,
    lng: 81.5212,
  },
  {
    id: "in-gnt",
    text: "Guntur",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["gnt"],
    lat: 16.3067,
    lng: 80.4365,
  },
  {
    id: "in-rjy",
    text: "Rajahmundry",
    secondary: "East Godavari, Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["rjy"],
    lat: 17.0005,
    lng: 81.804,
  },
  {
    id: "in-kak",
    text: "Kakinada",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["cct", "coa"],
    lat: 16.9891,
    lng: 82.2475,
  },
  {
    id: "in-knl",
    text: "Kurnool",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["knl"],
    lat: 15.8281,
    lng: 78.0373,
  },
  {
    id: "in-nlr",
    text: "Nellore",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["nlr"],
    lat: 14.4426,
    lng: 79.9865,
  },
  {
    id: "in-atp",
    text: "Anantapur",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["atp"],
    lat: 14.6819,
    lng: 77.6006,
  },
  {
    id: "in-ogl",
    text: "Ongole",
    secondary: "Prakasam, Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["ogl"],
    lat: 15.5057,
    lng: 80.0499,
  },
  {
    id: "in-ee",
    text: "Eluru",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["ee"],
    lat: 16.7107,
    lng: 81.0952,
  },
  {
    id: "in-kdp",
    text: "Kadapa",
    secondary: "Andhra Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["cuddapah", "cdp"],
    lat: 14.4673,
    lng: 78.8242,
  },
  {
    id: "in-wgl",
    text: "Warangal",
    secondary: "Telangana, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["kazipet", "wgl", "kzj"],
    lat: 17.9689,
    lng: 79.5941,
  },
  {
    id: "in-kmt",
    text: "Khammam",
    secondary: "Telangana, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["kmt"],
    lat: 17.2473,
    lng: 80.1514,
  },
  {
    id: "in-kzn",
    text: "Karimnagar",
    secondary: "Telangana, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    lat: 18.4386,
    lng: 79.1288,
  },
  {
    id: "in-nzb",
    text: "Nizamabad",
    secondary: "Telangana, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    lat: 18.6725,
    lng: 78.0941,
  },

  // --- INDIA - MAJOR METROS & HUBS ---
  {
    id: "in-blr",
    text: "Bangalore",
    secondary: "Karnataka, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bengaluru", "blr", "sbc", "silicon valley of india"],
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: "in-blr-air",
    text: "Kempegowda International Airport (BLR)",
    secondary: "Bangalore, Karnataka, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["blr", "airport", "devenahalli"],
    lat: 13.1986,
    lng: 77.7066,
  },
  {
    id: "in-che",
    text: "Chennai",
    secondary: "Tamil Nadu, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["madras", "mas", "maa", "central"],
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "in-che-air",
    text: "Chennai International Airport (MAA)",
    secondary: "Chennai, Tamil Nadu, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["maa", "meenambakkam"],
    lat: 12.9941,
    lng: 80.1709,
  },
  {
    id: "in-mum",
    text: "Mumbai",
    secondary: "Maharashtra, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bombay", "bom", "csmt", "cst", "marine drive"],
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "in-mum-air",
    text: "Chhatrapati Shivaji Maharaj Airport (BOM)",
    secondary: "Mumbai, Maharashtra, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["bom", "sahar", "santacruz"],
    lat: 19.0896,
    lng: 72.8656,
  },
  {
    id: "in-del",
    text: "Delhi",
    secondary: "India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["new delhi", "ndls", "del", "dli", "ncr"],
    lat: 28.6139,
    lng: 77.209,
  },
  {
    id: "in-del-air",
    text: "Indira Gandhi International Airport (DEL)",
    secondary: "New Delhi, India",
    type: "airport",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["del", "igi", "terminal 3"],
    lat: 28.5562,
    lng: 77.1,
  },
  {
    id: "in-kol",
    text: "Kolkata",
    secondary: "West Bengal, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["calcutta", "ccu", "howrah", "hwh", "sealdah"],
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    id: "in-pun",
    text: "Pune",
    secondary: "Maharashtra, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["pnq"],
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    id: "in-ahm",
    text: "Ahmedabad",
    secondary: "Gujarat, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["amd"],
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    id: "in-goa",
    text: "Goa",
    secondary: "India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["panaji", "madgaon", "dabolim", "mopa", "goi", "gox", "calangute"],
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: "in-koc",
    text: "Kochi",
    secondary: "Kerala, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["cochin", "cok", "ernakulam"],
    lat: 9.9312,
    lng: 76.2673,
  },
  {
    id: "in-jai",
    text: "Jaipur",
    secondary: "Rajasthan, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["pink city", "jai"],
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    id: "in-lko",
    text: "Lucknow",
    secondary: "Uttar Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["lko"],
    lat: 26.8467,
    lng: 80.9462,
  },
  {
    id: "in-var",
    text: "Varanasi",
    secondary: "Uttar Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["banaras", "kashi", "bsb", "vns", "ghats"],
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    id: "in-agr",
    text: "Agra",
    secondary: "Uttar Pradesh, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["taj mahal", "agc"],
    lat: 27.1767,
    lng: 78.0081,
  },
  {
    id: "in-chd",
    text: "Chandigarh",
    secondary: "India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["ixc"],
    lat: 30.7333,
    lng: 76.7794,
  },
  {
    id: "in-cbe",
    text: "Coimbatore",
    secondary: "Tamil Nadu, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["cbe", "cjb"],
    lat: 11.0168,
    lng: 76.9558,
  },
  {
    id: "in-mys",
    text: "Mysore",
    secondary: "Karnataka, India",
    type: "city",
    country: "India",
    currency: "INR",
    currencySymbol: "₹",
    keywords: ["mysuru", "mys"],
    lat: 12.2958,
    lng: 76.6394,
  },

  // --- UNITED KINGDOM & IRELAND ---
  {
    id: "gb-lon",
    text: "London",
    secondary: "United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["uk", "england", "big ben", "lhr", "lgw", "stpancras"],
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    id: "gb-lon-lhr",
    text: "Heathrow Airport (LHR)",
    secondary: "London, United Kingdom",
    type: "airport",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["lhr", "heathrow", "london airport"],
    lat: 51.47,
    lng: -0.4543,
  },
  {
    id: "gb-lon-stp",
    text: "St Pancras International (Eurostar)",
    secondary: "London, United Kingdom",
    type: "station",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["st pancras", "kings cross", "eurostar"],
    lat: 51.5314,
    lng: -0.1261,
  },
  {
    id: "gb-edi",
    text: "Edinburgh",
    secondary: "Scotland, United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["scotland", "edi", "waverley"],
    lat: 55.9533,
    lng: -3.1883,
  },
  {
    id: "gb-man",
    text: "Manchester",
    secondary: "United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["man", "piccadilly"],
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: "gb-bir",
    text: "Birmingham",
    secondary: "United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["bhx", "new street"],
    lat: 52.4862,
    lng: -1.8904,
  },
  {
    id: "gb-oxf",
    text: "Oxford",
    secondary: "United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["oxford university"],
    lat: 51.752,
    lng: -1.2577,
  },
  {
    id: "gb-cam",
    text: "Cambridge",
    secondary: "United Kingdom",
    type: "city",
    country: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    keywords: ["cambridge university"],
    lat: 52.2053,
    lng: 0.1218,
  },
  {
    id: "ie-dub",
    text: "Dublin",
    secondary: "Ireland",
    type: "city",
    country: "Ireland",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["ireland", "dub", "connolly", "heuston"],
    lat: 53.3498,
    lng: -6.2603,
  },

  // --- WESTERN & CENTRAL EUROPE ---
  {
    id: "fr-par",
    text: "Paris",
    secondary: "France",
    type: "city",
    country: "France",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["eiffel tower", "cdg", "orly", "gare du nord", "louvre"],
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    id: "fr-par-cdg",
    text: "Charles de Gaulle Airport (CDG)",
    secondary: "Paris, France",
    type: "airport",
    country: "France",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["cdg", "roissy"],
    lat: 49.0097,
    lng: 2.5479,
  },
  {
    id: "fr-par-gdn",
    text: "Gare du Nord (Eurostar / TGV)",
    secondary: "Paris, France",
    type: "station",
    country: "France",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["gare du nord", "tgv", "eurostar", "thalys"],
    lat: 48.8809,
    lng: 2.3553,
  },
  {
    id: "fr-nic",
    text: "Nice",
    secondary: "Côte d'Azur, France",
    type: "city",
    country: "France",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["french riviera", "nce"],
    lat: 43.7102,
    lng: 7.262,
  },
  {
    id: "fr-lyo",
    text: "Lyon",
    secondary: "France",
    type: "city",
    country: "France",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["lys", "part dieu"],
    lat: 45.764,
    lng: 4.8357,
  },
  {
    id: "de-ber",
    text: "Berlin",
    secondary: "Germany",
    type: "city",
    country: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["ber", "hauptbahnhof", "brandenburg gate"],
    lat: 52.52,
    lng: 13.405,
  },
  {
    id: "de-mun",
    text: "Munich",
    secondary: "Bavaria, Germany",
    type: "city",
    country: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["muc", "münchen", "oktoberfest"],
    lat: 48.1351,
    lng: 11.582,
  },
  {
    id: "de-fra",
    text: "Frankfurt",
    secondary: "Germany",
    type: "city",
    country: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["fra", "frankfurt airport", "main"],
    lat: 50.1109,
    lng: 8.6821,
  },
  {
    id: "de-ham",
    text: "Hamburg",
    secondary: "Germany",
    type: "city",
    country: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["ham"],
    lat: 53.5511,
    lng: 9.9937,
  },
  {
    id: "nl-ams",
    text: "Amsterdam",
    secondary: "Netherlands",
    type: "city",
    country: "Netherlands",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["holland", "ams", "schiphol", "centraal"],
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    id: "be-bru",
    text: "Brussels",
    secondary: "Belgium",
    type: "city",
    country: "Belgium",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["bru", "bruxelles", "midi"],
    lat: 50.8503,
    lng: 4.3517,
  },
  {
    id: "ch-zrh",
    text: "Zurich",
    secondary: "Switzerland",
    type: "city",
    country: "Switzerland",
    currency: "CHF",
    currencySymbol: "CHF ",
    keywords: ["zrh", "swiss", "hauptbahnhof"],
    lat: 47.3769,
    lng: 8.5417,
  },
  {
    id: "ch-gva",
    text: "Geneva",
    secondary: "Switzerland",
    type: "city",
    country: "Switzerland",
    currency: "CHF",
    currencySymbol: "CHF ",
    keywords: ["gva", "lake geneva"],
    lat: 46.2044,
    lng: 6.1432,
  },
  {
    id: "at-vie",
    text: "Vienna",
    secondary: "Austria",
    type: "city",
    country: "Austria",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["wien", "vie", "hauptbahnhof"],
    lat: 48.2082,
    lng: 16.3738,
  },
  {
    id: "cz-prg",
    text: "Prague",
    secondary: "Czech Republic",
    type: "city",
    country: "Czech Republic",
    currency: "CZK",
    currencySymbol: "Kč ",
    keywords: ["praha", "prg"],
    lat: 50.0755,
    lng: 14.4378,
  },

  // --- SOUTHERN EUROPE & MEDITERRANEAN ---
  {
    id: "it-rom",
    text: "Rome",
    secondary: "Italy",
    type: "city",
    country: "Italy",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["fco", "roma", "termini", "colosseum", "vatican"],
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    id: "it-mil",
    text: "Milan",
    secondary: "Lombardy, Italy",
    type: "city",
    country: "Italy",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["mxp", "milano", "centrale", "duomo"],
    lat: 45.4642,
    lng: 9.19,
  },
  {
    id: "it-ven",
    text: "Venice",
    secondary: "Italy",
    type: "city",
    country: "Italy",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["venezia", "vce", "santa lucia", "canals"],
    lat: 45.4408,
    lng: 12.3155,
  },
  {
    id: "it-flo",
    text: "Florence",
    secondary: "Tuscany, Italy",
    type: "city",
    country: "Italy",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["firenze", "flr", "santa maria novella"],
    lat: 43.7696,
    lng: 11.2558,
  },
  {
    id: "es-bcn",
    text: "Barcelona",
    secondary: "Catalonia, Spain",
    type: "city",
    country: "Spain",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["bcn", "sants", "sagrada familia"],
    lat: 41.3879,
    lng: 2.1699,
  },
  {
    id: "es-mad",
    text: "Madrid",
    secondary: "Spain",
    type: "city",
    country: "Spain",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["mad", "atocha", "barajas"],
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    id: "es-sev",
    text: "Seville",
    secondary: "Andalusia, Spain",
    type: "city",
    country: "Spain",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["svq", "sevilla", "santa justa"],
    lat: 37.3891,
    lng: -5.9845,
  },
  {
    id: "pt-lis",
    text: "Lisbon",
    secondary: "Portugal",
    type: "city",
    country: "Portugal",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["lis", "lisboa", "oriente", "santa apolonia"],
    lat: 38.7223,
    lng: -9.1393,
  },
  {
    id: "pt-opo",
    text: "Porto",
    secondary: "Portugal",
    type: "city",
    country: "Portugal",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["opo", "campanha"],
    lat: 41.1579,
    lng: -8.6291,
  },
  {
    id: "gr-ath",
    text: "Athens",
    secondary: "Greece",
    type: "city",
    country: "Greece",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["ath", "acropolis", "piraeus"],
    lat: 37.9838,
    lng: 23.7275,
  },
  {
    id: "gr-jtr",
    text: "Santorini",
    secondary: "Cyclades, Greece",
    type: "city",
    country: "Greece",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["jtr", "thira", "oia"],
    lat: 36.3932,
    lng: 25.4615,
  },

  // --- NORDICS ---
  {
    id: "se-sto",
    text: "Stockholm",
    secondary: "Sweden",
    type: "city",
    country: "Sweden",
    currency: "SEK",
    currencySymbol: "kr ",
    keywords: ["arn", "stockholm central"],
    lat: 59.3293,
    lng: 18.0686,
  },
  {
    id: "no-osl",
    text: "Oslo",
    secondary: "Norway",
    type: "city",
    country: "Norway",
    currency: "NOK",
    currencySymbol: "kr ",
    keywords: ["osl", "oslo s"],
    lat: 59.9139,
    lng: 10.7522,
  },
  {
    id: "dk-cph",
    text: "Copenhagen",
    secondary: "Denmark",
    type: "city",
    country: "Denmark",
    currency: "DKK",
    currencySymbol: "kr ",
    keywords: ["cph", "københavn"],
    lat: 55.6761,
    lng: 12.5683,
  },
  {
    id: "fi-hel",
    text: "Helsinki",
    secondary: "Finland",
    type: "city",
    country: "Finland",
    currency: "EUR",
    currencySymbol: "€",
    keywords: ["hel"],
    lat: 60.1699,
    lng: 24.9384,
  },
  {
    id: "is-kef",
    text: "Reykjavik",
    secondary: "Iceland",
    type: "city",
    country: "Iceland",
    currency: "ISK",
    currencySymbol: "kr ",
    keywords: ["kef", "iceland", "blue lagoon"],
    lat: 64.1466,
    lng: -21.9426,
  },

  // --- NORTH AMERICA - USA & CANADA ---
  {
    id: "us-nyc",
    text: "New York",
    secondary: "NY, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: [
      "nyc",
      "jfk",
      "ewr",
      "lga",
      "manhattan",
      "penn station",
      "grand central",
      "times square",
    ],
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "us-nyc-jfk",
    text: "John F. Kennedy International Airport (JFK)",
    secondary: "New York, NY, United States",
    type: "airport",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["jfk", "queens"],
    lat: 40.6413,
    lng: -73.7781,
  },
  {
    id: "us-bos",
    text: "Boston",
    secondary: "MA, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["bos", "logan", "south station", "cambridge", "harvard"],
    lat: 42.3601,
    lng: -71.0589,
  },
  {
    id: "us-was",
    text: "Washington, D.C.",
    secondary: "District of Columbia, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["dc", "iad", "dca", "union station", "capitol"],
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    id: "us-chi",
    text: "Chicago",
    secondary: "IL, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["ord", "mdw", "union station", "windy city", "loop"],
    lat: 41.8781,
    lng: -87.6298,
  },
  {
    id: "us-sfo",
    text: "San Francisco",
    secondary: "CA, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["sfo", "bay area", "silicon valley", "golden gate"],
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: "us-lax",
    text: "Los Angeles",
    secondary: "CA, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["lax", "hollywood", "union station", "santa monica"],
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: "us-sea",
    text: "Seattle",
    secondary: "WA, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["sea", "seatac", "space needle"],
    lat: 47.6062,
    lng: -122.3321,
  },
  {
    id: "us-las",
    text: "Las Vegas",
    secondary: "NV, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["las", "strip", "vegas"],
    lat: 36.1699,
    lng: -115.1398,
  },
  {
    id: "us-mia",
    text: "Miami",
    secondary: "FL, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["mia", "south beach"],
    lat: 25.7617,
    lng: -80.1918,
  },
  {
    id: "us-orl",
    text: "Orlando",
    secondary: "FL, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["mco", "disney", "universal"],
    lat: 28.5383,
    lng: -81.3792,
  },
  {
    id: "us-aus",
    text: "Austin",
    secondary: "TX, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["aus", "texas"],
    lat: 30.2672,
    lng: -97.7431,
  },
  {
    id: "us-dfw",
    text: "Dallas",
    secondary: "TX, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["dfw"],
    lat: 32.7767,
    lng: -96.797,
  },
  {
    id: "us-phi",
    text: "Philadelphia",
    secondary: "PA, United States",
    type: "city",
    country: "United States",
    currency: "USD",
    currencySymbol: "$",
    keywords: ["phl", "30th street"],
    lat: 39.9526,
    lng: -75.1652,
  },
  {
    id: "ca-yyz",
    text: "Toronto",
    secondary: "Ontario, Canada",
    type: "city",
    country: "Canada",
    currency: "CAD",
    currencySymbol: "C$",
    keywords: ["yyz", "union station", "cn tower"],
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: "ca-yvr",
    text: "Vancouver",
    secondary: "BC, Canada",
    type: "city",
    country: "Canada",
    currency: "CAD",
    currencySymbol: "C$",
    keywords: ["yvr", "pacific central"],
    lat: 49.2827,
    lng: -123.1207,
  },
  {
    id: "ca-yul",
    text: "Montreal",
    secondary: "Quebec, Canada",
    type: "city",
    country: "Canada",
    currency: "CAD",
    currencySymbol: "C$",
    keywords: ["yul", "gare centrale"],
    lat: 45.5017,
    lng: -73.5673,
  },
  {
    id: "mx-mex",
    text: "Mexico City",
    secondary: "Mexico",
    type: "city",
    country: "Mexico",
    currency: "MXN",
    currencySymbol: "Mex$ ",
    keywords: ["mex", "cdmx", "benito juarez"],
    lat: 19.4326,
    lng: -99.1332,
  },

  // --- ASIA & EAST ASIA ---
  {
    id: "jp-tok",
    text: "Tokyo",
    secondary: "Japan",
    type: "city",
    country: "Japan",
    currency: "JPY",
    currencySymbol: "¥",
    keywords: [
      "hnd",
      "nrt",
      "haneda",
      "narita",
      "shinjuku",
      "shibuya",
      "tokyo station",
      "shinkansen",
    ],
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    id: "jp-kyo",
    text: "Kyoto",
    secondary: "Japan",
    type: "city",
    country: "Japan",
    currency: "JPY",
    currencySymbol: "¥",
    keywords: ["kyoto station", "shinkansen", "gion", "kansai"],
    lat: 35.0116,
    lng: 135.7681,
  },
  {
    id: "jp-osa",
    text: "Osaka",
    secondary: "Japan",
    type: "city",
    country: "Japan",
    currency: "JPY",
    currencySymbol: "¥",
    keywords: ["kix", "itm", "shin-osaka", "dotonbori"],
    lat: 34.6937,
    lng: 135.5023,
  },
  {
    id: "kr-sel",
    text: "Seoul",
    secondary: "South Korea",
    type: "city",
    country: "South Korea",
    currency: "KRW",
    currencySymbol: "₩",
    keywords: ["icn", "gmp", "incheon", "seoul station", "ktx"],
    lat: 37.5665,
    lng: 126.978,
  },
  {
    id: "kr-pus",
    text: "Busan",
    secondary: "South Korea",
    type: "city",
    country: "South Korea",
    currency: "KRW",
    currencySymbol: "₩",
    keywords: ["pus", "ktx"],
    lat: 35.1796,
    lng: 129.0756,
  },
  {
    id: "cn-bjs",
    text: "Beijing",
    secondary: "China",
    type: "city",
    country: "China",
    currency: "CNY",
    currencySymbol: "¥",
    keywords: ["pek", "pkx", "capital", "forbidden city"],
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    id: "cn-sha",
    text: "Shanghai",
    secondary: "China",
    type: "city",
    country: "China",
    currency: "CNY",
    currencySymbol: "¥",
    keywords: ["pvg", "sha", "pudong", "hongqiao", "the bund"],
    lat: 31.2304,
    lng: 121.4737,
  },
  {
    id: "hk-hkg",
    text: "Hong Kong",
    secondary: "Hong Kong SAR",
    type: "city",
    country: "Hong Kong",
    currency: "HKD",
    currencySymbol: "HK$",
    keywords: ["hkg", "kowloon", "central", "chep lap kok"],
    lat: 22.3193,
    lng: 114.1694,
  },
  {
    id: "tw-tpe",
    text: "Taipei",
    secondary: "Taiwan",
    type: "city",
    country: "Taiwan",
    currency: "TWD",
    currencySymbol: "NT$",
    keywords: ["tpe", "taoyuan", "main station", "thsr"],
    lat: 25.033,
    lng: 121.5654,
  },

  // --- SOUTHEAST ASIA ---
  {
    id: "sg-sin",
    text: "Singapore",
    secondary: "Singapore",
    type: "city",
    country: "Singapore",
    currency: "SGD",
    currencySymbol: "S$",
    keywords: ["sin", "changi", "marina bay"],
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: "sg-sin-changi",
    text: "Singapore Changi Airport (SIN)",
    secondary: "Singapore",
    type: "airport",
    country: "Singapore",
    currency: "SGD",
    currencySymbol: "S$",
    keywords: ["changi", "jewel", "sin"],
    lat: 1.3644,
    lng: 103.9915,
  },
  {
    id: "th-bkk",
    text: "Bangkok",
    secondary: "Thailand",
    type: "city",
    country: "Thailand",
    currency: "THB",
    currencySymbol: "฿",
    keywords: ["bkk", "dmk", "suvarnabhumi", "don mueang", "krung thep"],
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: "th-hkt",
    text: "Phuket",
    secondary: "Thailand",
    type: "city",
    country: "Thailand",
    currency: "THB",
    currencySymbol: "฿",
    keywords: ["hkt", "patong"],
    lat: 7.8804,
    lng: 98.3923,
  },
  {
    id: "my-kul",
    text: "Kuala Lumpur",
    secondary: "Malaysia",
    type: "city",
    country: "Malaysia",
    currency: "MYR",
    currencySymbol: "RM ",
    keywords: ["kul", "klia", "kl sentral", "petronas"],
    lat: 3.139,
    lng: 101.6869,
  },
  {
    id: "id-dps",
    text: "Bali (Denpasar)",
    secondary: "Indonesia",
    type: "city",
    country: "Indonesia",
    currency: "IDR",
    currencySymbol: "Rp ",
    keywords: ["dps", "ngurah rai", "ubud", "kuta", "seminyak"],
    lat: -8.4095,
    lng: 115.1889,
  },
  {
    id: "id-jkt",
    text: "Jakarta",
    secondary: "Indonesia",
    type: "city",
    country: "Indonesia",
    currency: "IDR",
    currencySymbol: "Rp ",
    keywords: ["cgk", "soekarno-hatta"],
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    id: "vn-han",
    text: "Hanoi",
    secondary: "Vietnam",
    type: "city",
    country: "Vietnam",
    currency: "VND",
    currencySymbol: "₫",
    keywords: ["han", "noi bai"],
    lat: 21.0285,
    lng: 105.8542,
  },
  {
    id: "vn-sgn",
    text: "Ho Chi Minh City",
    secondary: "Vietnam",
    type: "city",
    country: "Vietnam",
    currency: "VND",
    currencySymbol: "₫",
    keywords: ["saigon", "sgn", "tan son nhat"],
    lat: 10.8231,
    lng: 106.6297,
  },

  // --- MIDDLE EAST ---
  {
    id: "ae-dxb",
    text: "Dubai",
    secondary: "United Arab Emirates",
    type: "city",
    country: "United Arab Emirates",
    currency: "AED",
    currencySymbol: "AED ",
    keywords: ["dxb", "burj khalifa", "uae", "emirates"],
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    id: "ae-dxb-air",
    text: "Dubai International Airport (DXB)",
    secondary: "Dubai, United Arab Emirates",
    type: "airport",
    country: "United Arab Emirates",
    currency: "AED",
    currencySymbol: "AED ",
    keywords: ["dxb", "emirates"],
    lat: 25.2532,
    lng: 55.3657,
  },
  {
    id: "ae-auh",
    text: "Abu Dhabi",
    secondary: "United Arab Emirates",
    type: "city",
    country: "United Arab Emirates",
    currency: "AED",
    currencySymbol: "AED ",
    keywords: ["auh", "etihad"],
    lat: 24.4539,
    lng: 54.3773,
  },
  {
    id: "qa-doh",
    text: "Doha",
    secondary: "Qatar",
    type: "city",
    country: "Qatar",
    currency: "QAR",
    currencySymbol: "QAR ",
    keywords: ["doh", "hamad international", "qatar airways"],
    lat: 25.2854,
    lng: 51.531,
  },
  {
    id: "sa-ruh",
    text: "Riyadh",
    secondary: "Saudi Arabia",
    type: "city",
    country: "Saudi Arabia",
    currency: "SAR",
    currencySymbol: "SAR ",
    keywords: ["ruh", "king khalid"],
    lat: 24.7136,
    lng: 46.6753,
  },
  {
    id: "sa-jed",
    text: "Jeddah",
    secondary: "Saudi Arabia",
    type: "city",
    country: "Saudi Arabia",
    currency: "SAR",
    currencySymbol: "SAR ",
    keywords: ["jed", "makkah gateway"],
    lat: 21.4858,
    lng: 39.1925,
  },
  {
    id: "tr-ist",
    text: "Istanbul",
    secondary: "Turkey",
    type: "city",
    country: "Turkey",
    currency: "TRY",
    currencySymbol: "₺",
    keywords: ["ist", "saw", "bosphorus"],
    lat: 41.0082,
    lng: 28.9784,
  },

  // --- AUSTRALIA & NEW ZEALAND ---
  {
    id: "au-syd",
    text: "Sydney",
    secondary: "NSW, Australia",
    type: "city",
    country: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    keywords: ["syd", "kingsford smith", "central station", "opera house"],
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    id: "au-mel",
    text: "Melbourne",
    secondary: "VIC, Australia",
    type: "city",
    country: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    keywords: ["mel", "southern cross", "flinders street"],
    lat: -37.8136,
    lng: 144.9631,
  },
  {
    id: "au-bne",
    text: "Brisbane",
    secondary: "QLD, Australia",
    type: "city",
    country: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    keywords: ["bne"],
    lat: -27.4698,
    lng: 153.0251,
  },
  {
    id: "au-per",
    text: "Perth",
    secondary: "WA, Australia",
    type: "city",
    country: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    keywords: ["per"],
    lat: -31.9505,
    lng: 115.8605,
  },
  {
    id: "nz-akl",
    text: "Auckland",
    secondary: "New Zealand",
    type: "city",
    country: "New Zealand",
    currency: "NZD",
    currencySymbol: "NZ$",
    keywords: ["akl", "britomart"],
    lat: -36.8485,
    lng: 174.7633,
  },

  // --- SOUTH AMERICA & AFRICA ---
  {
    id: "br-sao",
    text: "São Paulo",
    secondary: "Brazil",
    type: "city",
    country: "Brazil",
    currency: "BRL",
    currencySymbol: "R$ ",
    keywords: ["gru", "cgh", "paulista"],
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    id: "br-rio",
    text: "Rio de Janeiro",
    secondary: "Brazil",
    type: "city",
    country: "Brazil",
    currency: "BRL",
    currencySymbol: "R$ ",
    keywords: ["gig", "sdu", "copacabana"],
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    id: "ar-bue",
    text: "Buenos Aires",
    secondary: "Argentina",
    type: "city",
    country: "Argentina",
    currency: "ARS",
    currencySymbol: "AR$ ",
    keywords: ["eze", "aep", "retiro"],
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    id: "eg-cai",
    text: "Cairo",
    secondary: "Egypt",
    type: "city",
    country: "Egypt",
    currency: "EGP",
    currencySymbol: "E£ ",
    keywords: ["cai", "pyramids", "giza", "ramsesses"],
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    id: "za-cpt",
    text: "Cape Town",
    secondary: "South Africa",
    type: "city",
    country: "South Africa",
    currency: "ZAR",
    currencySymbol: "R ",
    keywords: ["cpt", "table mountain"],
    lat: -33.9249,
    lng: 18.4241,
  },
  {
    id: "za-jnb",
    text: "Johannesburg",
    secondary: "South Africa",
    type: "city",
    country: "South Africa",
    currency: "ZAR",
    currencySymbol: "R ",
    keywords: ["jnb", "or tambo"],
    lat: -26.2041,
    lng: 28.0473,
  },
];

export function getCurrencyForPlace(placeName: string): { symbol: string; code: string } {
  const pLower = placeName.toLowerCase();
  const matched = COMPREHENSIVE_PLACES.find(
    (p) =>
      p.text.toLowerCase().includes(pLower) ||
      pLower.includes(p.text.toLowerCase()) ||
      (p.country && pLower.includes(p.country.toLowerCase())),
  );
  if (matched?.currencySymbol && matched?.currency) {
    return { symbol: matched.currencySymbol, code: matched.currency };
  }

  // Geographic heuristics
  if (pLower.includes("india") || pLower.includes("andhra") || pLower.includes("telangana")) {
    return { symbol: "₹", code: "INR" };
  }
  if (
    pLower.includes("united kingdom") ||
    pLower.includes("uk") ||
    pLower.includes("london") ||
    pLower.includes("scotland") ||
    pLower.includes("england")
  ) {
    return { symbol: "£", code: "GBP" };
  }
  if (
    pLower.includes("france") ||
    pLower.includes("germany") ||
    pLower.includes("italy") ||
    pLower.includes("spain") ||
    pLower.includes("europe") ||
    pLower.includes("paris") ||
    pLower.includes("rome") ||
    pLower.includes("berlin") ||
    pLower.includes("amsterdam")
  ) {
    return { symbol: "€", code: "EUR" };
  }
  if (pLower.includes("japan") || pLower.includes("tokyo") || pLower.includes("kyoto")) {
    return { symbol: "¥", code: "JPY" };
  }
  if (pLower.includes("singapore")) {
    return { symbol: "S$", code: "SGD" };
  }
  if (pLower.includes("dubai") || pLower.includes("uae") || pLower.includes("emirates")) {
    return { symbol: "AED ", code: "AED" };
  }
  if (pLower.includes("australia") || pLower.includes("sydney") || pLower.includes("melbourne")) {
    return { symbol: "A$", code: "AUD" };
  }
  if (pLower.includes("canada") || pLower.includes("toronto") || pLower.includes("vancouver")) {
    return { symbol: "C$", code: "CAD" };
  }
  return { symbol: "$", code: "USD" };
}

export function searchInternalPlaces(query: string, maxResults = 10): PlaceEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return COMPREHENSIVE_PLACES.slice(0, maxResults);
  }

  const exactPrefix: PlaceEntry[] = [];
  const wordPrefix: PlaceEntry[] = [];
  const keywordMatches: PlaceEntry[] = [];
  const containsMatches: PlaceEntry[] = [];
  const seen = new Set<string>();

  for (const place of COMPREHENSIVE_PLACES) {
    const nameLower = place.text.toLowerCase();
    const secLower = place.secondary.toLowerCase();
    const key = place.id;

    if (nameLower.startsWith(q)) {
      exactPrefix.push(place);
      seen.add(key);
      continue;
    }

    const words = nameLower.split(/[\s,–()/-]+/);
    if (words.some((w) => w.startsWith(q))) {
      wordPrefix.push(place);
      seen.add(key);
      continue;
    }

    if (
      place.keywords?.some((k) => k.toLowerCase().startsWith(q) || k.toLowerCase() === q) ||
      (place.country && place.country.toLowerCase().startsWith(q))
    ) {
      keywordMatches.push(place);
      seen.add(key);
      continue;
    }

    if (nameLower.includes(q) || secLower.includes(q)) {
      containsMatches.push(place);
      seen.add(key);
    }
  }

  const combined = [...exactPrefix, ...wordPrefix, ...keywordMatches, ...containsMatches];
  return combined.slice(0, maxResults);
}
